// <auto-generated />
using System;
using DuneDominion.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuneDominion.Persistence.Migrations
{
    [DbContext(typeof(DunitaDbContext))]
    partial class DunitaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuneDominion.Shared.Criatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApetitoBase")
                        .HasColumnType("integer");

                    b.Property<int>("CosteCompra")
                        .HasColumnType("integer");

                    b.Property<int>("EdadActual")
                        .HasColumnType("integer");

                    b.Property<int>("EdadAdulta")
                        .HasColumnType("integer");

                    b.Property<string>("InstalacionCodigo")
                        .HasColumnType("text");

                    b.Property<int>("MedioRequerido")
                        .HasColumnType("integer");

                    b.Property<string>("NombreEspecie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatronAlimentacion")
                        .HasColumnType("integer");

                    b.Property<int>("Salud")
                        .HasColumnType("integer");

                    b.Property<int>("VecesFavorita")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionCodigo");

                    b.ToTable("Criaturas");
                });

            modelBuilder.Entity("DuneDominion.Shared.Enclave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Hectareas")
                        .HasColumnType("integer");

                    b.Property<int>("NivelPublico")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartidaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Suministros")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("VisitantesMensuales")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Enclaves");
                });

            modelBuilder.Entity("DuneDominion.Shared.Instalacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<int>("AlimentacionSoportada")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadCriaturas")
                        .HasColumnType("integer");

                    b.Property<int>("Coste")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EnclaveId")
                        .HasColumnType("uuid");

                    b.Property<int>("HectareasOcupadas")
                        .HasColumnType("integer");

                    b.Property<int>("MedioSoportado")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRecinto")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.HasIndex("EnclaveId");

                    b.ToTable("Instalaciones");
                });

            modelBuilder.Entity("DuneDominion.Shared.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasJugador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MesActual")
                        .HasColumnType("integer");

                    b.Property<string>("RegistroEventos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Solaris")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("DuneDominion.Shared.Criatura", b =>
                {
                    b.HasOne("DuneDominion.Shared.Instalacion", null)
                        .WithMany("CriaturasAlojadas")
                        .HasForeignKey("InstalacionCodigo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DuneDominion.Shared.Enclave", b =>
                {
                    b.HasOne("DuneDominion.Shared.Partida", null)
                        .WithMany("Enclaves")
                        .HasForeignKey("PartidaId");
                });

            modelBuilder.Entity("DuneDominion.Shared.Instalacion", b =>
                {
                    b.HasOne("DuneDominion.Shared.Enclave", null)
                        .WithMany("Instalaciones")
                        .HasForeignKey("EnclaveId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DuneDominion.Shared.Enclave", b =>
                {
                    b.Navigation("Instalaciones");
                });

            modelBuilder.Entity("DuneDominion.Shared.Instalacion", b =>
                {
                    b.Navigation("CriaturasAlojadas");
                });

            modelBuilder.Entity("DuneDominion.Shared.Partida", b =>
                {
                    b.Navigation("Enclaves");
                });
#pragma warning restore 612, 618
        }
    }
}
